// angular-learn/github-login-firebase/src/app/pages/signin/signin.component.ts
import { Component, OnInit } from '@angular/core';
import { NgForm } from '@angular/forms';

import { Router } from '@angular/router';
import { ToastrService } from 'ngx-toastr';
import { AuthService } from './../../services/auth.service';

@Component({
  selector: 'app-signin',
  templateUrl: './signin.component.html',
  styleUrls: ['./signin.component.css'],
})
export class SigninComponent implements OnInit {
  constructor(
    private auth: AuthService,
    private router: Router,
    private toastr: ToastrService
  ) {}

  ngOnInit(): void {}

  onSubmit(f: NgForm) {
    const { email, password } = f.form.value;
    //TODO: do your checking here
    this.auth
      .signIn(email, password)
      .then((res) => {
        this.router.navigateByUrl('/');
        this.toastr.success('Sign in Success');
      })
      .catch((err) => {
        console.log(err.message);
        this.toastr.error('Invalid credentials');
      });
  }
}

<div class="container">
  <div class="row mt-5">
    <div class="col col-6 offset-3">
      <div class="card">
        <div class="card-header text-center text-dark text-uppercase">
          Sign In Please
        </div>

        <div class="card-body">
          <form (ngSubmit)="onSubmit(f)" #f="ngForm">
            <div class="form-group row">
              <label for="email" class="col-sm-3 col-form-label">Email</label>
              <div class="col-sm-9">
                <input
                  type="email"
                  class="form-control"
                  id="email"
                  name="email"
                  ngModel
                  placeholder="Enter Email"
                  required
                />
              </div>
            </div>

            <div class="form-group row">
              <label for="password" class="col-sm-3 col-form-label"
                >Password</label
              >
              <div class="col-sm-9">
                <input
                  type="password"
                  class="form-control"
                  id="password"
                  name="password"
                  ngModel
                  placeholder="Enter password"
                  required
                />
                <small id="emailHelp" class="form-text text-muted"
                  >Minimum length of the password should be 6 or more</small
                >
              </div>
            </div>

            <div class="text-center">
              <button class="btn btn-dark" type="submit">
                Sign In
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

// react_learn/ten-firebase-github-app/src/pages/SignIn.js
import React, { useContext, useState } from "react";
import {
    Container,
    Form,
    Button,
    FormGroup,
    Label,
    Col,
    Input,
    Row,
    Card,
    CardBody,
    CardFooter,
    CardHeader,
} from "reactstrap";

import { getAuth, signInWithEmailAndPassword } from "firebase/auth";
import {UserContext} from "./../context/UserContext";
import { Navigate } from "react-router-dom";
import {toast} from "react-toastify";

const SignIn = ()=>{
    const context = useContext(UserContext);
    const [email,setEmail] = useState('');
    const [password,setPassword]=useState('');
    const auth = getAuth();
    const handleSignUp = () =>{
        signInWithEmailAndPassword(auth,email,password)
        .then(res => {
            console.log(res)
            context.setUser({email: res.user.email,uid: res.user.uid})
        })
        .catch(error=> {
            console.log(error)
            toast(error.message,{
                type:"error"
            })
        }
        
        )  
    }

    const handleSubmit =  e =>{
        e.preventDefault()
        handleSignUp()
    }
    
    if (context.user?.uid) {
        return <Navigate to="/" />
    }
    return (
		<Container className='text-center'>
			<Row>
				<Col lg={6} className='offset-lg-3 mt-5'>
					<Card>
						<Form onSubmit={handleSubmit}>
							<CardHeader className=''>Sign in here</CardHeader>
							<CardBody>
								<FormGroup row>
									<Label for='email' sm={3}>
										Email
									</Label>
									<Col sm={9}>
										<Input
											type='email'
											name='email'
											id='email'
											placeholder='provide your email'
											value={email}
											onChange={e => setEmail(e.target.value)}
										/>
									</Col>
								</FormGroup>
								<FormGroup row>
									<Label for='password' sm={3}>
										Password
									</Label>
									<Col sm={9}>
										<Input
											type='password'
											name='password'
											id='password'
											placeholder='your password here'
											value={password}
											onChange={e => setPassword(e.target.value)}
										/>
									</Col>
								</FormGroup>
							</CardBody>
							<CardFooter>
								<Button type='submit' block color='dark'>
									Sign In
								</Button>
							</CardFooter>
						</Form>
					</Card>
				</Col>
			</Row>
		</Container>
	);

    
}

export default SignIn
