// react_learn/three-state-counter/src/App.js
import React,{useState} from 'react';
import './App.css';

function App() {
  const [count,setCount] = useState(0)
  return (
   <div className='App'>
    <header>
      <h1>Counter app using state/hooks</h1>
    </header>
    <h2>Current value of count is {count}</h2>
    <button onClick={()=> setCount(0)}>Reset</button>
    <button onClick={()=> count>=10 ? "" : setCount(count+1)}>Increase counter</button>
    <button onClick={()=> count<=0 ? "" : setCount(count-1)}>Decrease counter</button>
   </div>
  );
}

export default App;

// angular-learn/counter-app/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title:string = 'Counter App';
  count:number = 0;
  

  handleIncrease = () => {
    if (this.count >= 10) {
      this.count = 10;
    }
    else{
      this.count = this.count + 1;
    }
    
  }

  handleDecrease = () => {
    if (this.count <= 0){
      this.count=0;
    }
    else {
      this.count = this.count - 1;
    }
  }

  handleReset = () => {
    this.count = 0;
  }
  




}

<div class="container">
  <header>
    <h1>{{ title }}</h1>
  </header>

  <main>
    <h2>Current Count is: {{count}}</h2>
  </main>

  <button (click)="handleReset()" >Reset Count</button>
  <button (click)="handleIncrease()" >Increase Count</button>
  <button (click)="handleDecrease()" >Decrease Count</button>


</div>
